version: "2"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodata:/data/db

  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redisdata:/data

  bot:
    build: .
    restart: always
    volumes:
      - ./:/app

  nsfw:
    build: ./nsfw_api
    restart: always
    volumes:
      - ./nsfw/.:/opt/nsfw
