name: Build Test

on: [push]

jobs:
  hexlightning:
    runs-on: ubuntu-latest
    name: build-hex
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests
    - name: Send Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat_id }}
        token: ${{ secrets.bot_token }}
        format: markdown
        message: |
          Action Trigger `${{ job.status }}`
          ==========
          Repo: `${{ github.repository }}`
          Actor: `${{ github.actor }}` `${{ github.event_name }}`
          Workflow: `${{ github.workflow }}`
          Commit: `${{ github.sha }}`
          ==========